spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginsPatterns: "*"
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
    discovery:
      client:
        health-indicator:
          enabled: false
#  data:
#    redis:
#      connect-timeout: 2s
#      host: localhost
#      port: 6379
#      timeout: 1s


#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"


jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    gateway:
      enabled: true
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Happy Food Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      sontruong02003:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000