deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

dataSource:
  url: jdbc:mysql://accountsdb:3307/accountsdb
  username: root
  password: root

replicaCount: 1

image:
  repository: sontruong02003/accounts
<<<<<<< HEAD
  tag: s1
=======
  tag: s2
>>>>>>> 284954572264b17e13bf877e6b0f8ab6e2d194d8

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

appname_enabled: true
profile_enabled: true
datasource_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false
database_enabled: false
<<<<<<< HEAD
allwayspull_enabled: true
=======
allwayspull_enabled: true
>>>>>>> 284954572264b17e13bf877e6b0f8ab6e2d194d8
