server:
  port: 9020

spring:
  application:
    name: chats
  profiles:
    active: "default"
  datasource:
#    url: jdbc:mysql://localhost:3310/chatsdb
    url: jdbc:mysql://localhost:3306/devdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
    openfeign:
      circuitbreaker:
        enabled: true
#    function:
#      definition: updateCommunication
#    stream:
#      bindings:
#        updateCommunication-in-0:
#          destination: communication-sent
#          group: ${spring.application.name}
#        sendCommunication-out-0:
#          destination: send-communication
#      kafka:
#        binder:
#          brokers:
#            - localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "chats"
    description: "ChatMessages Application"
    version: "1.0.0"

logging:
  level:
    com:
      sontruong02003:
        chats: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000
      limitRefreshPeriod: 5000
      limitForPeriod: 5

openai:
  api:
    key: "sk-"
    url: "https://api.openai.com/v1/chat/completions"
    model: "gpt-3.5-turbo"
    temperature: 0.7
    max_tokens: 1000
    top_p: 1
    frequency_penalty: 0
    presence_penalty: 0
    prompt: "Chào bạn, tôi là Sơn"