deploymentName: media-deployment
serviceName: media
appLabel: media
appName: media


replicaCount: 1

image:
  repository: sontruong02003/media
  tag: s1

containerPort: 9000

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

appname_enabled: true
profile_enabled: true
datasource_enabled: false
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false
database_enabled: false
allwayspull_enabled: true
