deploymentName: organizationposts-deployment
serviceName: organizationposts
appLabel: organizationposts
appName: organizationposts

dataSource:
  url: jdbc:mysql://organizationpostsdb:3309/organizationpostsdb
  username: root
  password: root

replicaCount: 1

image:
  repository: sontruong02003/organizationposts
  tag: s1

containerPort: 9010

service:
  type: ClusterIP
  port: 9010
  targetPort: 9010

appname_enabled: true
profile_enabled: true
datasource_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false
database_enabled: false
