server:
  port: 8090
spring:
  application:
    name: posts
  profiles:
    active: "default"
  datasource:
#    url: jdbc:mysql://localhost:3308/postsdb
    url: jdbc:mysql://localhost:3306/devdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
    openfeign:
      circuitbreaker:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "posts"
    description: "Posts Application"
    version: "1.0.0"

logging:
  level:
    com:
      sontruong02003:
        posts: DEBUG
    feign: DEBUG
    feign.Logger: DEBUG
    feign.codec: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

#resilience4j.circuitbreaker:
#  configs:
#    default:
#      slidingWindowSize: 10
#      permittedNumberOfCallsInHalfOpenState: 2
#      failureRateThreshold: 50
#      waitDurationInOpenState: 20s
#
#resilience4j.retry:
#  configs:
#    default:
#      maxRetryAttempts: 3
#      waitDuration: 1s
#      enableExponentialBackoff: true
#      exponentialBackoffMultiplier: 2
#
#resilience4j.ratelimiter:
#  configs:
#    default:
#      timeoutDuration: 20s
#      limitRefreshPeriod: 20s
#      limitForPeriod: 20

#  {
#    "Version": "2012-10-17",
#    "Statement": [
#      {
#        "Sid": "PublicReadGetObject",
#        "Effect": "Allow",
#        "Principal": "*",
#        "Action": "s3:GetObject",
#        "Resource": "arn:aws:s3:::tvhson/*"
#      }
#    ]
#  }